export type QuestionType =
  | "text"
  | "url"
  | "email"
  | "phone"
  | "long-text"
  | "single-select"
  | "multi-select"
  | "checkbox"
  | "address"
  | "file"
  | "group";

export interface QuestionOption {
  label: string;
  value: string;
}

export interface Question {
  id: string;
  number: number;
  question: string;
  type: QuestionType;
  required: boolean;
  options?: QuestionOption[];
  placeholder?: string;
  conditionalOn?: { questionId: string; value: string };
  section: string;
  subsection: string;
}

export interface QuestionSection {
  id: string;
  title: string;
  subsections: { id: string; title: string }[];
}

export const questionSections: QuestionSection[] = [
  {
    id: "company-profile",
    title: "Company Profile",
    subsections: [
      { id: "company-contacts", title: "Company & Contacts" },
      { id: "presence-scale", title: "Presence & Scale" },
      { id: "positioning-goals", title: "Positioning & Goals" },
    ],
  },
  {
    id: "segment-selection",
    title: "Service Selection",
    subsections: [{ id: "segment", title: "Select Your Services" }],
  },
  {
    id: "b2b",
    title: "B2B — Lead Generation",
    subsections: [
      { id: "b2b-package", title: "Package Selection" },
      { id: "b2b-target", title: "Target Market" },
      { id: "b2b-decision", title: "Decision-Maker Profile" },
      { id: "b2b-sales", title: "Sales Process" },
      { id: "b2b-setup", title: "Current Setup" },
      { id: "b2b-campaign", title: "Campaign Strategy" },
      { id: "b2b-reporting", title: "Reporting & Add-ons" },
    ],
  },
  {
    id: "b2g",
    title: "B2G — Government Contracts",
    subsections: [
      { id: "b2g-package", title: "Package Selection" },
      { id: "b2g-scope", title: "Target Scope" },
      { id: "b2g-capacity", title: "Capacity & Experience" },
      { id: "b2g-compliance", title: "Partnerships & Compliance" },
      { id: "b2g-evaluation", title: "Evaluation & Priorities" },
      { id: "b2g-reporting", title: "Reporting & Add-ons" },
    ],
  },
  {
    id: "adam",
    title: "A.D.A.M. — System Licensing",
    subsections: [
      { id: "adam-package", title: "Package Selection" },
      { id: "adam-company", title: "Company Details" },
      { id: "adam-onboarding", title: "Onboarding Assessment" },
      { id: "adam-config", title: "Configuration" },
      { id: "adam-future", title: "Future Plans" },
    ],
  },
  {
    id: "attachments",
    title: "Attachments",
    subsections: [{ id: "uploads", title: "Upload Documents" }],
  },
  {
    id: "review",
    title: "Review & Submit",
    subsections: [{ id: "review-submit", title: "Review Your Answers" }],
  },
];

export const questions: Question[] = [
  // Section 1: Company Profile — Company & Contacts
  {
    id: "companyName",
    number: 1,
    question: "What is your legal company name (as in official registration)?",
    type: "text",
    required: true,
    placeholder: "e.g. Acme Corporation Ltd",
    section: "company-profile",
    subsection: "company-contacts",
  },
  {
    id: "websiteUrl",
    number: 2,
    question: "What is your website URL?",
    type: "url",
    required: false,
    placeholder: "https://example.com",
    section: "company-profile",
    subsection: "company-contacts",
  },
  {
    id: "billingCurrency",
    number: 3,
    question: "What is your preferred billing currency?",
    type: "single-select",
    required: true,
    options: [
      { label: "EUR (€)", value: "EUR" },
      { label: "GBP (£)", value: "GBP" },
      { label: "USD ($)", value: "USD" },
      { label: "Other", value: "Other" },
    ],
    section: "company-profile",
    subsection: "company-contacts",
  },
  {
    id: "contactName",
    number: 4,
    question: "Contact person for business communication (full name)?",
    type: "text",
    required: true,
    placeholder: "John Smith",
    section: "company-profile",
    subsection: "company-contacts",
  },
  {
    id: "contactPhone",
    number: 5,
    question: "Contact person phone number?",
    type: "phone",
    required: true,
    placeholder: "+44 20 1234 5678",
    section: "company-profile",
    subsection: "company-contacts",
  },
  {
    id: "contactEmail",
    number: 6,
    question: "Contact person email address?",
    type: "email",
    required: true,
    placeholder: "john@example.com",
    section: "company-profile",
    subsection: "company-contacts",
  },
  {
    id: "address",
    number: 7,
    question: "What is your registered business address?",
    type: "address",
    required: true,
    section: "company-profile",
    subsection: "company-contacts",
  },
  {
    id: "dataEnrichmentConsent",
    number: 8,
    question:
      "I agree to data enrichment using public sources and official registers",
    type: "checkbox",
    required: true,
    section: "company-profile",
    subsection: "company-contacts",
  },
  // Section 1: Presence & Scale
  {
    id: "socialProfiles",
    number: 9,
    question: "LinkedIn / Social profiles?",
    type: "text",
    required: false,
    placeholder: "https://linkedin.com/company/...",
    section: "company-profile",
    subsection: "presence-scale",
  },
  {
    id: "countriesOfOperation",
    number: 10,
    question: "Which countries do you operate in?",
    type: "text",
    required: true,
    placeholder: "UK, Germany, Netherlands...",
    section: "company-profile",
    subsection: "presence-scale",
  },
  {
    id: "yearsInBusiness",
    number: 11,
    question: "How many years has your business been operating?",
    type: "single-select",
    required: true,
    options: [
      { label: "< 1 year", value: "<1" },
      { label: "1–3 years", value: "1-3" },
      { label: "3–5 years", value: "3-5" },
      { label: "5–10 years", value: "5-10" },
      { label: "10+ years", value: "10+" },
    ],
    section: "company-profile",
    subsection: "presence-scale",
  },
  {
    id: "annualRevenue",
    number: 12,
    question: "What is your annual revenue range?",
    type: "single-select",
    required: false,
    options: [
      { label: "< €100K", value: "<100K" },
      { label: "€100K–€500K", value: "100K-500K" },
      { label: "€500K–€1M", value: "500K-1M" },
      { label: "€1M–€5M", value: "1M-5M" },
      { label: "€5M–€20M", value: "5M-20M" },
      { label: "€20M+", value: "20M+" },
      { label: "Prefer not to say", value: "undisclosed" },
    ],
    section: "company-profile",
    subsection: "presence-scale",
  },
  // Section 1: Positioning & Goals
  {
    id: "productsServices",
    number: 13,
    question: "What are your key products or services?",
    type: "long-text",
    required: true,
    placeholder: "Describe your main offerings...",
    section: "company-profile",
    subsection: "positioning-goals",
  },
  {
    id: "businessGoals",
    number: 14,
    question: "What are your primary business goals for the next 12 months?",
    type: "long-text",
    required: true,
    placeholder: "e.g. Expand to new markets, increase revenue by 50%...",
    section: "company-profile",
    subsection: "positioning-goals",
  },
  {
    id: "challenges",
    number: 15,
    question: "What are the main challenges you currently face?",
    type: "long-text",
    required: true,
    placeholder: "Describe your biggest pain points...",
    section: "company-profile",
    subsection: "positioning-goals",
  },
  {
    id: "competitors",
    number: 16,
    question:
      "Who are the competitors you want to outperform? (name and website)",
    type: "long-text",
    required: false,
    placeholder: "Competitor 1: example.com\nCompetitor 2: example2.com",
    section: "company-profile",
    subsection: "positioning-goals",
  },
  {
    id: "usp",
    number: 17,
    question: "What are your unique selling points (USPs)?",
    type: "long-text",
    required: true,
    placeholder: "What makes you different from competitors?",
    section: "company-profile",
    subsection: "positioning-goals",
  },
  {
    id: "communicationChannels",
    number: 18,
    question:
      "What are your preferred communication channels with clients?",
    type: "multi-select",
    required: true,
    options: [
      { label: "Email", value: "email" },
      { label: "Chat", value: "chat" },
      { label: "SMS", value: "sms" },
      { label: "Phone", value: "phone" },
      { label: "Video calls", value: "video" },
      { label: "Other", value: "other" },
    ],
    section: "company-profile",
    subsection: "positioning-goals",
  },
  {
    id: "securityRequirements",
    number: 19,
    question: "Do you have any specific data security requirements?",
    type: "multi-select",
    required: false,
    options: [
      { label: "Special storage", value: "special-storage" },
      { label: "Encryption", value: "encryption" },
      { label: "GDPR", value: "gdpr" },
      { label: "HIPAA", value: "hipaa" },
      { label: "On-premise hosting", value: "on-premise" },
      { label: "Other", value: "other" },
    ],
    section: "company-profile",
    subsection: "positioning-goals",
  },
  {
    id: "privacyPolicyAgreed",
    number: 20,
    question: "I agree to the Privacy Policy",
    type: "checkbox",
    required: true,
    section: "company-profile",
    subsection: "positioning-goals",
  },
  // Section 2: Segment Selection
  {
    id: "segments",
    number: 21,
    question: "Which service type(s) are you interested in?",
    type: "multi-select",
    required: true,
    options: [
      {
        label: "B2B — Lead Generation & Sales Development",
        value: "B2B",
      },
      {
        label: "B2G — Public Tender & Government Contracts",
        value: "B2G",
      },
      {
        label: "A.D.A.M. — Automation System Licensing",
        value: "ADAM",
      },
    ],
    section: "segment-selection",
    subsection: "segment",
  },
  // Section 3: B2B
  {
    id: "b2bPackage",
    number: 22,
    question: "Choose your B2B package",
    type: "single-select",
    required: true,
    options: [
      { label: "CORE (€950/mo)", value: "CORE" },
      { label: "ADVANCE (€1,350/mo)", value: "ADVANCE" },
      { label: "VANGUARD (€1,750/mo)", value: "VANGUARD" },
      { label: "PRESTIGE (from €2,400/mo)", value: "PRESTIGE" },
    ],
    section: "b2b",
    subsection: "b2b-package",
  },
  {
    id: "b2bTargetCountries",
    number: 23,
    question: "What are your target countries / regions?",
    type: "text",
    required: true,
    placeholder: "e.g. DACH region, Nordics, UK...",
    section: "b2b",
    subsection: "b2b-target",
  },
  {
    id: "b2bTargetIndustries",
    number: 24,
    question: "What are your preferred target industries?",
    type: "text",
    required: true,
    placeholder: "e.g. SaaS, Manufacturing, Healthcare...",
    section: "b2b",
    subsection: "b2b-target",
  },
  {
    id: "b2bCompanySize",
    number: 25,
    question: "What is your preferred target company size?",
    type: "multi-select",
    required: true,
    options: [
      { label: "1–10 employees", value: "1-10" },
      { label: "11–50 employees", value: "11-50" },
      { label: "51–200 employees", value: "51-200" },
      { label: "201–1000 employees", value: "201-1000" },
      { label: "1000+ employees", value: "1000+" },
    ],
    section: "b2b",
    subsection: "b2b-target",
  },
  {
    id: "b2bContactRoles",
    number: 26,
    question: "What contact roles do you prefer to target?",
    type: "multi-select",
    required: true,
    options: [
      { label: "CEO", value: "CEO" },
      { label: "CMO", value: "CMO" },
      { label: "Procurement", value: "Procurement" },
      { label: "CTO", value: "CTO" },
      { label: "CFO", value: "CFO" },
      { label: "Sales Director", value: "Sales Director" },
      { label: "Marketing Director", value: "Marketing Director" },
      { label: "Other", value: "Other" },
    ],
    section: "b2b",
    subsection: "b2b-decision",
  },
  {
    id: "b2bSeniority",
    number: 27,
    question: "What decision-maker seniority do you target?",
    type: "multi-select",
    required: true,
    options: [
      { label: "C-Level", value: "C-Level" },
      { label: "VP / Director", value: "VP/Director" },
      { label: "Manager", value: "Manager" },
      { label: "Team Lead", value: "Team Lead" },
      { label: "Other", value: "Other" },
    ],
    section: "b2b",
    subsection: "b2b-decision",
  },
  {
    id: "b2bSalesCycle",
    number: 28,
    question: "What is your typical sales cycle length?",
    type: "single-select",
    required: true,
    options: [
      { label: "Short (< 1 month)", value: "short" },
      { label: "Medium (1–3 months)", value: "medium" },
      { label: "Long (> 3 months)", value: "long" },
    ],
    section: "b2b",
    subsection: "b2b-sales",
  },
  {
    id: "b2bCurrentDealSize",
    number: 29,
    question: "What is your current average deal size?",
    type: "text",
    required: false,
    placeholder: "e.g. €5,000",
    section: "b2b",
    subsection: "b2b-sales",
  },
  {
    id: "b2bTargetDealSize",
    number: 30,
    question: "What is your target deal size?",
    type: "text",
    required: false,
    placeholder: "e.g. €10,000",
    section: "b2b",
    subsection: "b2b-sales",
  },
  {
    id: "b2bSellingChannels",
    number: 31,
    question: "What selling channels do you currently use?",
    type: "multi-select",
    required: true,
    options: [
      { label: "Email", value: "email" },
      { label: "Cold call", value: "cold-call" },
      { label: "LinkedIn", value: "linkedin" },
      { label: "Events", value: "events" },
      { label: "Referrals", value: "referrals" },
      { label: "Content marketing", value: "content" },
      { label: "Other", value: "other" },
    ],
    section: "b2b",
    subsection: "b2b-sales",
  },
  {
    id: "b2bOutreachLanguages",
    number: 32,
    question: "What outreach language(s) are required?",
    type: "text",
    required: true,
    placeholder: "e.g. English, German, French",
    section: "b2b",
    subsection: "b2b-sales",
  },
  {
    id: "b2bCrm",
    number: 33,
    question: 'What CRM system do you use? (or "none")',
    type: "text",
    required: true,
    placeholder: "e.g. HubSpot, Salesforce, none",
    section: "b2b",
    subsection: "b2b-setup",
  },
  {
    id: "b2bConversionRate",
    number: 34,
    question: "What is your current lead conversion rate (%)?",
    type: "text",
    required: false,
    placeholder: "e.g. 5%",
    section: "b2b",
    subsection: "b2b-setup",
  },
  {
    id: "b2bObjections",
    number: 35,
    question: "What are the top 3 client objections you usually face?",
    type: "long-text",
    required: false,
    placeholder: "1. Price too high\n2. Already have a solution\n3. ...",
    section: "b2b",
    subsection: "b2b-setup",
  },
  {
    id: "b2bDecisionTriggers",
    number: 36,
    question: "What are the key decision triggers for your buyers?",
    type: "multi-select",
    required: true,
    options: [
      { label: "Discounts", value: "discounts" },
      { label: "Compliance", value: "compliance" },
      { label: "Innovation", value: "innovation" },
      { label: "Speed", value: "speed" },
      { label: "Quality", value: "quality" },
      { label: "Support", value: "support" },
      { label: "Other", value: "other" },
    ],
    section: "b2b",
    subsection: "b2b-campaign",
  },
  {
    id: "b2bProductsToPromote",
    number: 37,
    question: "Which specific products/services do you want to promote?",
    type: "long-text",
    required: true,
    placeholder: "Describe the products or services for this campaign...",
    section: "b2b",
    subsection: "b2b-campaign",
  },
  {
    id: "b2bMarketingMaterial",
    number: 38,
    question: "What marketing material do you have available?",
    type: "multi-select",
    required: false,
    options: [
      { label: "Pitch deck", value: "pitch-deck" },
      { label: "Brochures", value: "brochures" },
      { label: "Videos", value: "videos" },
      { label: "Case studies", value: "case-studies" },
      { label: "White papers", value: "white-papers" },
      { label: "Product demos", value: "demos" },
      { label: "Other", value: "other" },
    ],
    section: "b2b",
    subsection: "b2b-campaign",
  },
  {
    id: "b2bPreviousMethods",
    number: 39,
    question:
      "What previous lead generation methods have you tried? What worked and what didn't?",
    type: "long-text",
    required: false,
    section: "b2b",
    subsection: "b2b-campaign",
  },
  {
    id: "b2bCompetitorStrengths",
    number: 40,
    question: "What competitor strengths do you need to counteract?",
    type: "long-text",
    required: false,
    section: "b2b",
    subsection: "b2b-campaign",
  },
  {
    id: "b2bCompliance",
    number: 41,
    question:
      "Any special compliance or certification requirements?",
    type: "long-text",
    required: false,
    section: "b2b",
    subsection: "b2b-campaign",
  },
  {
    id: "b2bReportingFormat",
    number: 42,
    question: "What is your preferred reporting format?",
    type: "single-select",
    required: true,
    options: [
      { label: "Google Sheets", value: "google-sheets" },
      { label: "PDF", value: "pdf" },
      { label: "CRM export", value: "crm-export" },
      { label: "Excel", value: "excel" },
      { label: "Other", value: "other" },
    ],
    section: "b2b",
    subsection: "b2b-reporting",
  },
  {
    id: "b2bAddons",
    number: 43,
    question: "Any optional B2B add-ons you'd like?",
    type: "multi-select",
    required: false,
    options: [
      { label: "Extra leads", value: "extra-leads" },
      { label: "CRM export setup", value: "crm-setup" },
      { label: "Multilingual scripts", value: "multilingual" },
      { label: "AI-powered proposal generation", value: "ai-proposals" },
      { label: "Custom branding", value: "custom-branding" },
      { label: "Multi-market expansion support", value: "multi-market" },
      { label: "Other", value: "other" },
    ],
    section: "b2b",
    subsection: "b2b-reporting",
  },
  // Section 4: B2G
  {
    id: "b2gPackage",
    number: 44,
    question: "Choose your B2G package",
    type: "single-select",
    required: true,
    options: [
      { label: "GovStarter (£650/mo)", value: "GovStarter" },
      { label: "GovExpand (£1,050/mo)", value: "GovExpand" },
      { label: "GovElite (£1,650/mo)", value: "GovElite" },
    ],
    section: "b2g",
    subsection: "b2g-package",
  },
  {
    id: "b2gTargetRegions",
    number: 45,
    question: "What regions are you targeting?",
    type: "single-select",
    required: true,
    options: [
      { label: "UK only", value: "UK" },
      { label: "EU only", value: "EU" },
      { label: "Both UK & EU", value: "UK+EU" },
    ],
    section: "b2g",
    subsection: "b2g-scope",
  },
  {
    id: "b2gTenderTypes",
    number: 46,
    question: "What tender types are you interested in?",
    type: "multi-select",
    required: true,
    options: [
      { label: "RFP", value: "RFP" },
      { label: "RFQ", value: "RFQ" },
      { label: "Grants", value: "Grants" },
      { label: "Frameworks", value: "Frameworks" },
      { label: "Other", value: "Other" },
    ],
    section: "b2g",
    subsection: "b2g-scope",
  },
  {
    id: "b2gCpvCodes",
    number: 47,
    question: "Relevant CPV codes (if known)?",
    type: "text",
    required: false,
    placeholder: "e.g. 72000000-5",
    section: "b2g",
    subsection: "b2g-scope",
  },
  {
    id: "b2gContractValue",
    number: 48,
    question: "What is your preferred contract value range?",
    type: "single-select",
    required: true,
    options: [
      { label: "< £50K", value: "<50K" },
      { label: "£50K–£150K", value: "50K-150K" },
      { label: "£150K–£500K", value: "150K-500K" },
      { label: "£500K–£1M", value: "500K-1M" },
      { label: "£1M+", value: "1M+" },
    ],
    section: "b2g",
    subsection: "b2g-scope",
  },
  {
    id: "b2gSectorFocus",
    number: 49,
    question: "What sector do you focus on?",
    type: "text",
    required: true,
    placeholder: "e.g. Healthcare, Defence, IT...",
    section: "b2g",
    subsection: "b2g-scope",
  },
  {
    id: "b2gKeywords",
    number: 50,
    question: "Tender search keywords?",
    type: "text",
    required: false,
    placeholder: "e.g. software development, consulting...",
    section: "b2g",
    subsection: "b2g-scope",
  },
  {
    id: "b2gSubmissionCapacity",
    number: 51,
    question: "How many submissions can you handle per month?",
    type: "text",
    required: true,
    placeholder: "e.g. 3-5",
    section: "b2g",
    subsection: "b2g-capacity",
  },
  {
    id: "b2gBidResources",
    number: 52,
    question:
      "What internal bid preparation resources do you have? (team size & experience)",
    type: "long-text",
    required: false,
    placeholder: "Team size: 2\nExperience: Intermediate",
    section: "b2g",
    subsection: "b2g-capacity",
  },
  {
    id: "b2gExperienceLevel",
    number: 53,
    question: "What is your tender experience level?",
    type: "single-select",
    required: true,
    options: [
      { label: "No experience", value: "none" },
      { label: "Beginner (1–3 bids)", value: "beginner" },
      { label: "Intermediate (4–10 bids)", value: "intermediate" },
      { label: "Experienced (10+ bids)", value: "experienced" },
    ],
    section: "b2g",
    subsection: "b2g-capacity",
  },
  {
    id: "b2gPastExperience",
    number: 54,
    question: "What is your past tender experience?",
    type: "single-select",
    required: true,
    options: [
      { label: "Won", value: "won" },
      { label: "Lost", value: "lost" },
      { label: "Never applied", value: "never" },
    ],
    section: "b2g",
    subsection: "b2g-capacity",
  },
  {
    id: "b2gFailureReasons",
    number: 55,
    question: "Main reasons for past unsuccessful bids (if applicable)?",
    type: "long-text",
    required: false,
    section: "b2g",
    subsection: "b2g-capacity",
  },
  {
    id: "b2gConsortium",
    number: 56,
    question: "Are you interested in consortium partnerships?",
    type: "single-select",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
    section: "b2g",
    subsection: "b2g-compliance",
  },
  {
    id: "b2gTranslation",
    number: 57,
    question: "Do you need translation support?",
    type: "single-select",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
    section: "b2g",
    subsection: "b2g-compliance",
  },
  {
    id: "b2gBidCompliance",
    number: 58,
    question: "What bid compliance requirements do you have?",
    type: "multi-select",
    required: false,
    options: [
      { label: "ISO certification", value: "iso" },
      { label: "GDPR compliance", value: "gdpr" },
      { label: "Insurance levels", value: "insurance" },
      { label: "Security clearance", value: "security" },
      { label: "Financial thresholds", value: "financial" },
      { label: "Other", value: "other" },
    ],
    section: "b2g",
    subsection: "b2g-compliance",
  },
  {
    id: "b2gEvaluationCriteria",
    number: 59,
    question: "What evaluation criteria are your priorities?",
    type: "multi-select",
    required: true,
    options: [
      { label: "Price", value: "price" },
      { label: "Quality", value: "quality" },
      { label: "Innovation", value: "innovation" },
      { label: "Sustainability", value: "sustainability" },
      { label: "Local content", value: "local" },
      { label: "Experience", value: "experience" },
      { label: "Other", value: "other" },
    ],
    section: "b2g",
    subsection: "b2g-evaluation",
  },
  {
    id: "b2gGrantInterest",
    number: 60,
    question: "Are you interested in grant applications?",
    type: "single-select",
    required: false,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
    section: "b2g",
    subsection: "b2g-evaluation",
  },
  {
    id: "b2gReportingFrequency",
    number: 61,
    question: "What is your preferred reporting frequency?",
    type: "single-select",
    required: true,
    options: [
      { label: "Weekly", value: "weekly" },
      { label: "Bi-weekly", value: "bi-weekly" },
      { label: "Monthly", value: "monthly" },
    ],
    section: "b2g",
    subsection: "b2g-reporting",
  },
  {
    id: "b2gAddons",
    number: 62,
    question: "Any optional B2G add-ons?",
    type: "multi-select",
    required: false,
    options: [
      { label: "Grant writing", value: "grant-writing" },
      { label: "Pitch deck creation", value: "pitch-deck" },
      { label: "Translation services", value: "translation" },
      { label: "Consortium matching", value: "consortium" },
      { label: "Other", value: "other" },
    ],
    section: "b2g",
    subsection: "b2g-reporting",
  },
  // Section 5: ADAM
  {
    id: "adamPackage",
    number: 63,
    question: "Choose your A.D.A.M. package",
    type: "single-select",
    required: true,
    options: [
      { label: "Starter", value: "Starter" },
      { label: "Professional", value: "Professional" },
      { label: "Enterprise", value: "Enterprise" },
    ],
    section: "adam",
    subsection: "adam-package",
  },
  {
    id: "adamBranding",
    number: 64,
    question: "Do you need a branding add-on?",
    type: "single-select",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
    section: "adam",
    subsection: "adam-package",
  },
  {
    id: "adamCompanyName",
    number: 65,
    question: "Full legal company name and registration number?",
    type: "text",
    required: true,
    section: "adam",
    subsection: "adam-company",
  },
  {
    id: "adamWebsite",
    number: 66,
    question: "Company website (to pull branding & copy)?",
    type: "url",
    required: true,
    placeholder: "https://example.com",
    section: "adam",
    subsection: "adam-company",
  },
  {
    id: "adamIndustry",
    number: 67,
    question: "What is your primary industry & target audience?",
    type: "text",
    required: true,
    section: "adam",
    subsection: "adam-company",
  },
  {
    id: "adamServicesCount",
    number: 68,
    question: "How many services/products do you offer?",
    type: "text",
    required: true,
    section: "adam",
    subsection: "adam-company",
  },
  {
    id: "adamExistingOnboarding",
    number: 69,
    question: "Do you have an existing client onboarding process?",
    type: "single-select",
    required: true,
    options: [
      { label: "Yes (describe below)", value: "yes" },
      { label: "No", value: "no" },
    ],
    section: "adam",
    subsection: "adam-onboarding",
  },
  {
    id: "adamOnboardingDescription",
    number: 70,
    question: "Describe your existing onboarding process",
    type: "long-text",
    required: false,
    conditionalOn: { questionId: "adamExistingOnboarding", value: "yes" },
    section: "adam",
    subsection: "adam-onboarding",
  },
  {
    id: "adamNewClientsPerMonth",
    number: 71,
    question: "Average number of new clients per month?",
    type: "text",
    required: true,
    section: "adam",
    subsection: "adam-onboarding",
  },
  {
    id: "adamBottlenecks",
    number: 72,
    question: "What are the main bottlenecks in your current onboarding?",
    type: "multi-select",
    required: true,
    options: [
      { label: "Time", value: "time" },
      { label: "Accuracy", value: "accuracy" },
      { label: "Follow-up", value: "follow-up" },
      { label: "Data errors", value: "data-errors" },
      { label: "Manual processes", value: "manual" },
      { label: "Communication gaps", value: "communication" },
      { label: "Other", value: "other" },
    ],
    section: "adam",
    subsection: "adam-onboarding",
  },
  {
    id: "adamServicePackages",
    number: 73,
    question: "Preferred service packages for your clients (if known)?",
    type: "long-text",
    required: false,
    section: "adam",
    subsection: "adam-config",
  },
  {
    id: "adamCustomTemplates",
    number: 74,
    question: "Do you require custom contract templates?",
    type: "single-select",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
    section: "adam",
    subsection: "adam-config",
  },
  {
    id: "adamConfigAddons",
    number: 75,
    question: "Any add-ons to include?",
    type: "multi-select",
    required: false,
    options: [
      { label: "Extra templates", value: "extra-templates" },
      { label: "CRM integration", value: "crm" },
      { label: "AI outreach scripts", value: "ai-outreach" },
      { label: "Other", value: "other" },
    ],
    section: "adam",
    subsection: "adam-config",
  },
  {
    id: "adamAdminUsers",
    number: 76,
    question: "How many admin panel users do you need?",
    type: "text",
    required: true,
    placeholder: "e.g. 3",
    section: "adam",
    subsection: "adam-config",
  },
  {
    id: "adamAiMode",
    number: 77,
    question: "What is your preferred AI mode?",
    type: "single-select",
    required: true,
    options: [
      { label: "Free AI (built-in)", value: "free" },
      { label: "OpenAI (premium)", value: "openai" },
      { label: "Custom / hybrid", value: "custom" },
    ],
    section: "adam",
    subsection: "adam-config",
  },
  {
    id: "adamLaunchDeadline",
    number: 78,
    question: "What is your launch deadline / urgency level?",
    type: "single-select",
    required: true,
    options: [
      { label: "Urgent (< 2 weeks)", value: "urgent" },
      { label: "Standard (2–4 weeks)", value: "standard" },
      { label: "Flexible (1–2 months)", value: "flexible" },
      { label: "No rush", value: "no-rush" },
    ],
    section: "adam",
    subsection: "adam-config",
  },
  {
    id: "adamFutureUpgrades",
    number: 79,
    question: "Any future upgrade interests?",
    type: "multi-select",
    required: false,
    options: [
      { label: "E.V.A. integration", value: "eva" },
      { label: "SaaS plan", value: "saas" },
      { label: "Custom modules", value: "custom" },
      { label: "Other", value: "other" },
    ],
    section: "adam",
    subsection: "adam-future",
  },
  // Section 6: Attachments
  {
    id: "attachments",
    number: 80,
    question:
      "Upload any supporting documents (pitch decks, brochures, brand guidelines, contracts, etc.)",
    type: "file",
    required: false,
    section: "attachments",
    subsection: "uploads",
  },
];

export function getQuestionsForSegments(selectedSegments: string[]): Question[] {
  const baseQuestions = questions.filter(
    (q) =>
      q.section === "company-profile" ||
      q.section === "segment-selection" ||
      q.section === "attachments" ||
      q.section === "review"
  );

  const segmentQuestions: Question[] = [];
  if (selectedSegments.includes("B2B")) {
    segmentQuestions.push(...questions.filter((q) => q.section === "b2b"));
  }
  if (selectedSegments.includes("B2G")) {
    segmentQuestions.push(...questions.filter((q) => q.section === "b2g"));
  }
  if (selectedSegments.includes("ADAM")) {
    segmentQuestions.push(...questions.filter((q) => q.section === "adam"));
  }

  return [...baseQuestions, ...segmentQuestions];
}
