import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Copyright Notice",
  description: "Copyright notice and intellectual property statement for A.D.A.M. by Andy'K Group International LTD.",
  alternates: { canonical: "/copyright" },
};

export default function CopyrightPage() {
  const year = new Date().getFullYear();

  return (
    <main className="min-h-screen bg-background">
      <div className="max-w-[760px] mx-auto px-6 py-16 md:py-24">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-muted-2 hover:text-muted transition-colors mb-10"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="shrink-0">
            <path d="M10 12L6 8L10 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          Back to home
        </Link>

        <h1 className="text-3xl md:text-4xl font-semibold text-foreground tracking-tight mb-2">
          Copyright Notice
        </h1>
        <p className="text-sm text-muted-2 font-mono mt-4 mb-10">
          &copy; {year} Andy&apos;K Group International LTD
        </p>

        <div className="border-t border-grid-300" />

        <article className="mt-10 space-y-8 text-[15px] leading-relaxed text-muted">

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Ownership</h2>
            <p>
              All content, design, code, workflows, templates, AI logic, generated documents,
              and all other elements of the A.D.A.M. platform are the property of or are
              licensed to Andy&apos;K Group International LTD (&ldquo;the Company&rdquo;),
              registered in England and Wales (Company No. 16453500).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Permitted use</h2>
            <p>
              Documents generated specifically for your engagement (proposals, contracts,
              invoices, strategies) are licensed to you for internal business use only
              under the terms of your active subscription and engagement agreement.
            </p>
            <p className="mt-2">
              You may not reproduce, redistribute, resell, publish, or create derivative
              works from any part of the A.D.A.M. platform or its outputs without prior
              written consent from Andy&apos;K Group International LTD.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Trademarks</h2>
            <p>
              &ldquo;A.D.A.M.&rdquo;, &ldquo;Andy&apos;K Group&rdquo;, and associated logos
              and marks are trademarks of Andy&apos;K Group International LTD. Unauthorised
              use of these marks is prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Reverse engineering</h2>
            <p>
              You may not reverse engineer, decompile, disassemble, or attempt to derive
              source code from any part of the A.D.A.M. platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">AI-generated content</h2>
            <p>
              Content generated by AI features within A.D.A.M. is produced using licensed
              third-party AI services. All output remains subject to these copyright terms.
              Clients may use AI-generated proposals and documents for their own business
              purposes under the terms of their subscription.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Contact</h2>
            <p>
              For copyright enquiries or licensing requests, contact:{" "}
              <a href="mailto:legal@andykgroup.com" className="underline underline-offset-2 hover:text-foreground transition-colors">
                legal@andykgroup.com
              </a>
            </p>
          </section>

          <div className="pt-4 border-t border-grid-300">
            <p className="text-sm text-muted-2">
              See also:{" "}
              <Link href="/terms-and-conditions" className="underline underline-offset-2 hover:text-foreground transition-colors">Terms &amp; Conditions</Link> &middot;{" "}
              <Link href="/disclaimer" className="underline underline-offset-2 hover:text-foreground transition-colors">Disclaimer</Link>
            </p>
          </div>
        </article>
      </div>
    </main>
  );
}
