import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Disclaimer for A.D.A.M. — the AI-Powered Business Development Operating System by Andy'K Group International LTD.",
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-background">
      <div className="max-w-[760px] mx-auto px-6 py-16 md:py-24">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-muted-2 hover:text-muted transition-colors mb-10"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="shrink-0">
            <path d="M10 12L6 8L10 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          Back to home
        </Link>

        <h1 className="text-3xl md:text-4xl font-semibold text-foreground tracking-tight mb-2">
          Disclaimer
        </h1>

        <p className="text-sm text-muted-2 font-mono mt-4 mb-10">
          Last updated: 25 May 2026
        </p>

        <div className="border-t border-grid-300" />

        <article className="mt-10 space-y-10 text-[15px] leading-relaxed text-muted">
          <p>
            This Disclaimer applies to the A.D.A.M. platform (adam.andykgroup.com) operated
            by Andy&apos;K Group International LTD (&ldquo;we&rdquo;, &ldquo;us&rdquo;,
            &ldquo;our&rdquo;). By using A.D.A.M., you accept this Disclaimer. If you do not
            agree, please do not use the platform.
          </p>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1) Informational purposes only</h2>
            <p>
              All content within A.D.A.M. — including proposals, summaries, strategy
              documents, and dashboard data — is provided for business informational purposes
              only. It does not constitute legal, tax, financial, accounting, procurement,
              compliance, or other professional advice.
            </p>
            <p className="mt-2">
              You should obtain independent professional advice before acting on any
              information generated by or displayed within A.D.A.M.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2) AI-generated content</h2>
            <p>
              A.D.A.M. uses artificial intelligence to generate proposals, executive
              summaries, and other documents based on information you provide. AI-generated
              content:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Is produced automatically and may contain errors or inaccuracies</li>
              <li>Is for discussion and drafting purposes only</li>
              <li>Is not legally binding unless reviewed, approved, and executed as a formal contract signed by both parties</li>
              <li>Should always be reviewed by a qualified human before being relied upon or acted on</li>
            </ul>
            <p className="mt-2">
              We do not warrant the accuracy, completeness, or suitability of any AI-generated
              content for any specific purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3) No client relationship created</h2>
            <p>
              Registering for A.D.A.M., submitting a questionnaire, or receiving an
              AI-generated proposal does not create a client-consultant relationship or any
              binding obligation on either party. A formal engagement is only established
              through a written contract executed by authorised representatives of both parties.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4) No guarantees — results may vary</h2>
            <p>
              Where A.D.A.M. is used in connection with business development, procurement,
              or client acquisition services, you acknowledge that outcomes depend on factors
              outside our control — including market conditions, third-party decisions, client
              readiness, and timing.
            </p>
            <p className="mt-2">
              Unless expressly agreed in a signed contract, we do not guarantee any specific
              business outcome, including leads generated, contracts won, revenue, or
              onboarding timelines.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5) Accuracy and updates</h2>
            <p>
              We aim to keep A.D.A.M. accurate and up to date, but we make no representations
              or warranties that the platform or its content is free from errors at all times.
              Platform features, workflows, and document templates may be updated or changed
              without notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6) Third-party services</h2>
            <p>
              A.D.A.M. integrates third-party services (including Supabase for data storage
              and Resend for email delivery). We are not responsible for the availability,
              security, or conduct of third-party providers. Your use of A.D.A.M. is subject
              to their respective terms and policies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7) Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, we will not be liable for any loss or
              damage arising from your use of A.D.A.M. or reliance on content generated by it,
              including any indirect, consequential, or special loss (including loss of profits,
              revenue, business, data, or goodwill).
            </p>
            <p className="mt-2">
              Nothing in this Disclaimer excludes or limits liability that cannot be excluded
              under applicable law, including liability for death or personal injury caused by
              negligence, fraud, or fraudulent misrepresentation.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8) Governing law</h2>
            <p>
              This Disclaimer is governed by the laws of England and Wales, and any disputes
              shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">9) Contact</h2>
            <p>
              If you have questions about this Disclaimer, contact us at:
            </p>
            <div className="mt-3 text-sm font-mono text-muted-2 space-y-0.5">
              <p className="font-medium text-foreground">Andy&apos;K Group International LTD</p>
              <p>Email: info@andykgroup.com</p>
              <p>Address: 86&ndash;90 Paul Street, London, EC2A 4NE, United Kingdom</p>
            </div>
          </section>
        </article>
      </div>
    </main>
  );
}
